engine:
  sites:
    - url: https://www.svetlovka.ru
      name: Светловка
      request-timeout: 500
    - url: https://www.skillbox.ru
      name: Skillbox
      request-timeout: 500
    - url: https://ipfran.ru
      name: Институт прикладной физики
      request-timeout: 500
    - url: https://volochek.life
      name: Вышний Волочек
      request-timeout: 500
    - url: http://radiomv.ru
      name: Радио "Милицейская Волна"
      request-timeout: 500
    - url:  https://dimonvideo.ru
      name: Димон Видео
      request-timeout: 500
    - url: https://nikoartgallery.com
      name: Галерея Искусств Niko
      request-timeout: 500
server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/websurfer?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-circular-references: true
  output:
    ansi:
      enabled: never
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
